require "json"
require "yaml"
require "fileutils"

ROOT = File.expand_path("../..", __dir__)
OUT_DIR = File.join(ROOT, "tmp", "openapi")
ROUTES_JSON_PATH = File.join(OUT_DIR, "routes.json")
COVERAGE_MD_PATH = File.join(OUT_DIR, "coverage.md")
HANDWRITTEN_YAML_PATH = File.join(ROOT, "docs", "openapi.yaml")
SPEC_DIR = File.join(ROOT, "spec", "controllers")

FileUtils.mkdir_p(OUT_DIR)

def normalize_path(spec_path)
  spec_path.to_s.sub(/\(\.:format\)\z/, "")
end

def normalize_verb(verb)
  return "ANY" if verb.nil? || verb.to_s.empty?
  verb.to_s.upcase.split("|").first
end

def spec_file_for(controller)
  return nil if controller.nil? || controller.empty?
  File.join(SPEC_DIR, "#{controller}_controller_spec.rb")
end

VERBS = %w[get post put patch delete head options trace].freeze

# Try YAML first; fall back to a tolerant regex scan of the `paths:` section
# if the spec contains content that trips Psych (e.g. unquoted colons in
# descriptions). We only need (verb, path) pairs, so the regex form is fine.
def collect_handwritten_endpoints(yaml_path)
  return {} unless File.exist?(yaml_path)
  begin
    data = YAML.safe_load_file(yaml_path, aliases: true, permitted_classes: [Symbol])
    paths = data["paths"] || {}
    result = {}
    paths.each do |raw_path, methods|
      next unless methods.is_a?(Hash)
      methods.each_key do |verb|
        next unless VERBS.include?(verb.to_s.downcase)
        result[[verb.to_s.upcase, raw_path]] = true
      end
    end
    return result
  rescue Psych::SyntaxError => e
    warn "[routes_scraper] YAML.safe_load_file failed (#{e.message}); falling back to regex scan."
  end

  scan_handwritten_endpoints_regex(yaml_path)
end

def scan_handwritten_endpoints_regex(yaml_path)
  result = {}
  in_paths = false
  current_path = nil
  path_indent = nil
  File.foreach(yaml_path) do |line|
    if !in_paths
      in_paths = true if line =~ /\Apaths:\s*\z/
      next
    end
    # Leaving the paths section if we hit another top-level key.
    if line =~ /\A[A-Za-z_]/
      break
    end
    next if line.strip.empty? || line.strip.start_with?("#")

    if (m = line.match(%r{\A(\s*)(/[^:\s]*)\s*:\s*\z}))
      indent = m[1].length
      if path_indent.nil? || indent <= path_indent
        path_indent = indent
        current_path = m[2]
      end
      next
    end

    if current_path && (m = line.match(/\A(\s*)([A-Za-z]+)\s*:\s*\z/))
      verb = m[2].downcase
      indent = m[1].length
      if VERBS.include?(verb) && path_indent && indent > path_indent
        result[[verb.upcase, current_path]] = true
      end
    end
  end
  result
end

# Convert a Rails-style path into the form used in docs/openapi.yaml. The
# handwritten spec's server URL is `https://api.gumroad.com/v2` (and
# `https://gumroad.com/api/v2`), so its `paths:` are relative to `/v2`, not
# `/api/v2`. Strip whichever prefix the Rails path uses, then convert ":foo"
# placeholders to "{foo}".
def to_handwritten_path(rails_path)
  stripped = rails_path
    .sub(%r{\A/api/v2}, "")
    .sub(%r{\A/v2}, "")
    .sub(%r{\A/api}, "")
  stripped = "/" if stripped.empty?
  stripped.gsub(/:([A-Za-z_][A-Za-z0-9_]*)/) { "{#{Regexp.last_match(1)}}" }
end

handwritten = collect_handwritten_endpoints(HANDWRITTEN_YAML_PATH)

# Ensure routes are loaded
Rails.application.reload_routes! unless Rails.application.routes.routes.any?

entries = []
Rails.application.routes.routes.each do |route|
  defaults = route.defaults || {}
  controller = defaults[:controller].to_s
  next unless controller.start_with?("api/v2/")

  action = defaults[:action].to_s
  verb = normalize_verb(route.verb)
  path = normalize_path(route.path.spec.to_s)
  name = route.name

  spec_file_abs = spec_file_for(controller)
  has_spec = spec_file_abs && File.exist?(spec_file_abs)
  spec_file_rel = has_spec ? spec_file_abs.sub("#{ROOT}/", "") : nil

  hw_path = to_handwritten_path(path)
  in_handwritten = handwritten.key?([verb, hw_path])

  entries << {
    "verb" => verb,
    "path" => path,
    "controller" => controller,
    "action" => action,
    "name" => name,
    "has_spec" => !!has_spec,
    "spec_file" => spec_file_rel,
    "in_handwritten_openapi" => in_handwritten,
  }
end

entries.sort_by! { |e| [e["path"], e["verb"], e["action"]] }

File.write(ROUTES_JSON_PATH, JSON.pretty_generate(entries) + "\n")

total = entries.size
with_spec = entries.count { |e| e["has_spec"] }
in_hw = entries.count { |e| e["in_handwritten_openapi"] }
blind_spots = entries.reject { |e| e["has_spec"] || e["in_handwritten_openapi"] }

pct = ->(n) { total.zero? ? "0.0%" : format("%.1f%%", (n.to_f / total) * 100) }

lines = []
lines << "# API v2 OpenAPI coverage"
lines << ""
lines << "Generated by `script/openapi/routes_scraper.rb`."
lines << ""
lines << "## Totals"
lines << ""
lines << "- Total v2 endpoints: **#{total}**"
lines << "- Endpoints with controller spec file: **#{with_spec}** (#{pct.call(with_spec)})"
lines << "- Endpoints present in `docs/openapi.yaml`: **#{in_hw}** (#{pct.call(in_hw)})"
lines << "- Blind spots (neither spec nor handwritten): **#{blind_spots.size}** (#{pct.call(blind_spots.size)})"
lines << ""
lines << "## All endpoints"
lines << ""
lines << "| Verb | Path | Controller#action | Spec | In openapi.yaml |"
lines << "| --- | --- | --- | :---: | :---: |"
entries.each do |e|
  spec_mark = e["has_spec"] ? "x" : " "
  hw_mark = e["in_handwritten_openapi"] ? "x" : " "
  lines << "| #{e['verb']} | `#{e['path']}` | `#{e['controller']}##{e['action']}` | [#{spec_mark}] | [#{hw_mark}] |"
end
lines << ""
lines << "## Blind spots"
lines << ""
lines << "Endpoints with neither a controller spec file nor a handwritten `docs/openapi.yaml` entry."
lines << ""
lines << "Note: `has_spec` is computed at controller granularity (the controller's spec file exists), not at action granularity. So every endpoint whose controller has any spec file is counted as `has_spec: true` here, even if that specific action is untested. A more granular spec-coverage check is downstream work."
lines << ""
if blind_spots.empty?
  lines << "_None under the controller-granularity rule above._"
else
  lines << "| Verb | Path | Controller#action |"
  lines << "| --- | --- | --- |"
  blind_spots.each do |e|
    lines << "| #{e['verb']} | `#{e['path']}` | `#{e['controller']}##{e['action']}` |"
  end
end
lines << ""

missing_from_handwritten = entries.reject { |e| e["in_handwritten_openapi"] }
lines << "## Missing from handwritten openapi.yaml"
lines << ""
lines << "Endpoints that exist in the Rails routes but are not documented in `docs/openapi.yaml`. These are the most useful targets for the generated spec to fill in."
lines << ""
if missing_from_handwritten.empty?
  lines << "_None._"
else
  lines << "| Verb | Path | Controller#action |"
  lines << "| --- | --- | --- |"
  missing_from_handwritten.each do |e|
    lines << "| #{e['verb']} | `#{e['path']}` | `#{e['controller']}##{e['action']}` |"
  end
end
lines << ""

File.write(COVERAGE_MD_PATH, lines.join("\n"))

puts "Wrote #{ROUTES_JSON_PATH} (#{total} endpoints)"
puts "Wrote #{COVERAGE_MD_PATH}"
puts "  with spec: #{with_spec} (#{pct.call(with_spec)})"
puts "  in handwritten: #{in_hw} (#{pct.call(in_hw)})"
puts "  blind spots: #{blind_spots.size}"
